---
- src: https://github.com/crgwilson/ansible-role-openssh
  version: master
  name: openssh

- src: https://github.com/crgwilson/ansible-role-users-and-groups
  version: master
  name: users_and_groups

- src: https://github.com/crgwilson/ansible-role-fish
  version: master
  name: fish

- src: https://github.com/crgwilson/ansible-role-packer
  version: master
  name: packer

- src: https://github.com/crgwilson/ansible-role-libvirt-host
  version: master
  name: libvirt_host

- src: https://github.com/crgwilson/ansible-role-debian-backports-repo
  version: master
  name: debian_backports_repo

- src: https://github.com/crgwilson/ansible-role-sudo
  version: master
  name: sudo

- src: https://github.com/crgwilson/ansible-role-hostname
  version: master
  name: hostname

- src: https://github.com/crgwilson/ansible-role-qemu-guest-agent
  version: master
  name: qemu-guest-agent

- src: https://github.com/crgwilson/ansible-role-rsyslog
  version: master
  name: rsyslog

- src: https://github.com/crgwilson/ansible-role-iptables
  version: master
  name: iptables

- src: https://github.com/crgwilson/ansible-role-docker-ce
  version: master
  name: docker-ce
