---
- src: https://github.com/crgwilson/ansible-role-openssh
  version: master
  name: crgwilson.openssh

- src: https://github.com/crgwilson/ansible-role-users-and-groups
  version: master
  name: crgwilson.users_and_groups

- src: https://github.com/crgwilson/ansible-role-fish
  version: master
  name: crgwilson.fish

- src: https://github.com/crgwilson/ansible-role-packer
  version: master
  name: crgwilson.packer

- src: https://github.com/crgwilson/ansible-role-libvirt-host
  version: master
  name: crgwilson.libvirt_host

- src: https://github.com/crgwilson/ansible-role-debian-backports-repo
  version: master
  name: crgwilson.debian_backports_repo

- src: https://github.com/crgwilson/ansible-role-epel
  version: master
  name: crgwilson.epel

- src: https://github.com/crgwilson/ansible-role-sudo
  version: master
  name: crgwilson.sudo

- src: https://github.com/crgwilson/ansible-role-hostname
  version: master
  name: crgwilson.hostname

- src: https://github.com/crgwilson/ansible-role-qemu-guest-agent
  version: master
  name: crgwilson.qemu-guest-agent

- src: https://github.com/crgwilson/ansible-role-rsyslog
  version: master
  name: crgwilson.rsyslog

- src: https://github.com/crgwilson/ansible-role-iptables
  version: master
  name: crgwilson.iptables

- src: https://github.com/crgwilson/ansible-role-gnupg
  version: master
  name: crgwilson.gnupg

- src: https://github.com/crgwilson/ansible-role-apt
  version: master
  name: crgwilson.apt

- src: https://github.com/crgwilson/ansible-role-docker-ce
  version: master
  name: crgwilson.docker-ce

- src: https://github.com/crgwilson/ansible-role-freeipa-client
  version: master
  name: crgwilson.freeipa-client

- src: https://github.com/crgwilson/ansible-role-git
  version: master
  name: crgwilson.git

- src: https://github.com/crgwilson/ansible-role-yocto
  version: master
  name: crgwilson.yocto
