---
- hosts: all
  roles:
    - role: crgwilson.hostname
      tags:
        - hostname
    - role: crgwilson.fish
      tags:
        - fish
    - role: crgwilson.users_and_groups
      tags:
        - users
        - groups
        - users_and_groups
    - role: crgwilson.sudo
      tags:
        - sudo
    - role: crgwilson.qemu-guest-agent
      when: ('virtual' in group_names)
      tags:
        - qemu-guest-agent
    - role: crgwilson.openssh
      tags:
        - ssh
        - openssh
    - role: crgwilson.docker-ce
      when: install_docker is defined
      tags:
        - docker
