---
- hosts: all
  roles:
    - role: fish
      tags:
        - fish
    - role: users_and_groups
      tags:
        - users
        - groups
        - users_and_groups
    - role: openssh
      tags:
        - ssh
        - openssh
