---
- hosts: all
  roles:
    - role: hostname
      tags:
        - hostname
    - role: fish
      tags:
        - fish
    - role: users_and_groups
      tags:
        - users
        - groups
        - users_and_groups
    - role: sudo
      tags:
        - sudo
    - role: qemu-guest-agent
      when: ('virtual' in group_names)
      tags:
        - qemu-guest-agent
    - role: openssh
      tags:
        - ssh
        - openssh
