---
- hosts: kvm_hypervisor
  roles:
    - role: crgwilson.libvirt_host
      tags: libvirt
    - role: crgwilson.packer
      tags: packer
    - role: crgwilson.debian_backports_repo
      tags:
        - debian
        - backports
        - apt
        - debian_backports_repo
    - role: crgwilson.yocto
